image: docker:latest

stages:
  - builds

variables:
  RELEASE: $DOCKER_USER/nginx_test:latest

before_script:
   - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

build:
  stage: build
  tags:
    - shared_runner
  script:
   - docker build --pull -t $RELEASE .
   - docker push $RELEASE
